currency table
sihorjs/web-push-currencies pull request #1
Opened 2022-09-26 08:56 UTC by Tatiana-256

Added table to show currency

2022-09-26 14:43 UTC, sihorjs requested changes
Fix small codestyle issue, please

2022-09-26 14:43 UTC, singvarr commented on package.json
> -    "react-scripts": "5.0.1",
Why did you downgrade `react-scripts`?

2022-09-26 14:43 UTC, singvarr commented on src/Table/hook.js
> +    fetch("http://localhost:3000")
rename env variable `SERVER_PORT to `REACT_APP_SERVER_PORT` and use here

2022-09-26 14:43 UTC, singvarr commented on src/Table/Table.js
> +import { useTable } from "./hook";
1. Don't move to a separate hook, put all logic in the component
2. Don't worry about error handling

2022-09-26 14:43 UTC, singvarr commented on src/Table/Table.js
> +import React from "react";
There is no need to import `react` everywhere

2022-09-26 14:43 UTC, singvarr commented on src/Table/Table.js
> +      sx={{ width: "70%" }}
remove `sx`, move all styles to CSS-module. I want to keep code with logic clean and simple

2022-09-29 07:39 UTC, Tatiana-256 commented on package.json
> -    "react-scripts": "5.0.1",
changed back

2022-09-29 07:39 UTC, Tatiana-256 commented on src/Table/hook.js
> +    fetch("http://localhost:3000")
done

2022-09-29 07:39 UTC, Tatiana-256 commented on src/Table/Table.js
> +import { useTable } from "./hook";
done

2022-09-29 07:43 UTC, Tatiana-256 commented on src/Table/Table.js
> +import React from "react";
done

2022-09-29 07:43 UTC, Tatiana-256 commented on src/Table/Table.js
> +      sx={{ width: "70%" }}
removed

2022-09-29 20:38 UTC, merged